name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ê¹€ì˜ì›…"
      - run: echo "990327"
      - run: echo "gupo941020@naver.com"
      - run: echo "01075743839"
      - run: echo "ì°½ì›ì‹œ ê±°ì£¼"
      - run: echo "ì°½ì›ëŒ€í•™êµ"
      - run: echo "ë¶€ì‚° ì¶œì‹ "















